name: Portfolio Deployment

on:
  push:
    branches:
    - master
jobs:
  my_job:
    name: build and  deploy
    runs-on: ubuntu-22.04   
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: azure cli setup
      uses: azure/setup-azurecli@v1

    - name: azure login
      uses: azure/login@v1
      with: 
       creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to Azure Blob Storage
      run: 
       az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --destination '$web' \
            --source Public/* 


