name: Portfolio Deployment

on:
  push:
    branches:
    - master
jobs:
  my_job:
    name: build and  deploy
    runs-on: ubuntu-22.04   
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1
     

    - name: Upload to Azure Blob Storage
      run: |
        AZURE_STORAGE_ACCOUNT=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
        az storage blob download-batch \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --account-key $AZURE_STORAGE_ACCOUNT_KEY \
            --destination ./site \
            --source '$web'

